### ISSUE TITLE
Lights never turn on/off, missing service? 

### ISSUE THREAD

**Issue by precz** [haberda/light_automation#5]
Hi, thanks for developing this!

I have an issue with making it work. 
I have seen your code calls `light/turn_on` service, but I have none service like this registered on my setup.
```
self.log(self.list_services(namespace="light"))
```
Outputs empty array. 

Could you help me what am I missing?

**Comment by haberda** [comment]
I don't think the namespace is light, I think it's 'default', light is a domain. Here is the output for the light domain: `{'namespace': 'default', 'domain': 'light', 'service': 'turn_on'}`, for the light turn on service. So the syntax is `domain/service` for `light/turn_on`. The namespace is not specified because it is default.

As to why your lights are not turning on, I am not sure. What does your app config look like?

**Comment by precz** [comment]
Hi, so now I figured out what my problem was. Part of my lights are actually a `switch` type instead of `light`. So service `light/turn_on` will not work in this case.
So maybe for making this app more functional we could switch to use `homeassistant.turn_on` service. Then user could manage any entity (that supports being turned on), for example an automation, switch, etc.

Thanks for your patience,
Paweł.

**Comment by haberda** [comment]
Ah, I see. If I expanded to have it do switches then I couldn't easily pass data like brightness and color like it does now. You can create a [light ](https://www.home-assistant.io/integrations/light.switch/) out of a switch with home assistant.

**Comment by precz** [comment]
You're right! I'll do that!

Thanks for your help!
